[tool.ruff]
target-version = "py312"
line-length = 120
extend-exclude = ["alembic"]

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.12"
files = ["app", "tests", "tests_api"]
ignore_missing_imports = true
strict = false
show_error_codes = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = false
no_implicit_optional = false

